application: floodsourcerhok
version: 1
runtime: python
api_version: 1

inbound_services:
- mail

handlers:

- url: /_ah/mail/.+
  script: handle_incoming_mail.py
  login: admin

- url: /css/(.*\.css)
  static_files: css/\1
  upload: css/(.*\.css)

- url: /js/(.*)
  static_files: js/\1
  upload: js/(.*)

- url: /.*
  script: floodsource.py


